sudo: required
dist: trusty
language: cpp
branches:
  only:
  - dev
addons:
  apt:
    packages:
    - g++-5
    sources:
    - ubuntu-toolchain-r-test
before-install:
- sudo apt-get update
install:
- sudo apt-get install libboost-dev
- sudo apt-get install doxygen
- sudo apt-get install libgtest-dev
- sudo apt-get install valgrind
- ls -al /usr/src
- cd /usr/src/gtest
- sudo cmake CMakeLists.txt
- sudo make
- sudo cp *.a /usr/lib
- cd -
before_script:
- uname -a
- printenv | sort
- apt list --installed
- make versions
script:
- date
- ls -al
- make test
env:
  global:
  - secure: dNR9wMkdjv9QTzPEtyVZBaca3FvmSrIm0BDmAZjDKTEavVWayPsdtlaRtDNVYc4AZQ/uvRfohfiY6wameYtsDslAV3M+4LU4QKQhY7eIOyO6uwWxKV2c5cusC7Y6ZbKhwg/iLVQdamn4oHrJP7WCIx5VqfSo24jJbXfnCvtBin4KFy3tuoAk2/rKXvcKoQqLFS4RHgOx5b/ntwl4aLW/WRu3EOsskuB9gs4Kg78WFclv1bWOaNJbMVHiqSSsAmvCuiZcGgpMtZBRqzX/II1x4kEHeSobOe9UrjwbzvoCy6sSveIet1EthHQ6+Q402w0qjGQoCVhdieOp9MXtiboZ7s3Fxl2xyNDSHb+VZ5c4iYOAZGhjOaBhFCzqZibsA5ktp35zzEs5aXod6Rm+b418D1qMmJ6KctX9wMCE/jAfS3dToYpIu/5T/ov0YAImskYKbSpobweV6qLaOfqK/q8CIekLJsyIkf0+Id2YDr80kaA/uH0HOAxonppnnveVa+0ohQgUH0iG04c2D7alH59+i2xW/oFYOIMW/pMeKr7T/TFQTQhPw3Jrktu2R22C0mi/pK8f4FqUafCAbXdY4lGxdrM+Pvw9vT4mWk0IgiGqeLBx+CNXG0GDVsu9KWWWXXq032RoUkpxxpJkqQotbKBshl5tg1ZFYyrz2O2967PxU6E=
  - secure: QyjlkCa9DjoiR2mOOZJ0jtgQtxAF38wi7pO/7toIFrmZJwpTdJOds0TDz/MPm7sG2b18aFl8FkFSlOFKGK76VeWEXrjdwJCkmhRmCKQlSb/KXaCvK9xCufFiHDyKEeuGIgiM0McTvGCWBwu9P1ZVQtX4Ehe5103ebfVEa+fVU41RtTnaSBMkcOdoj0bPqMdm1EcnuQfgJJMi2jb9nUsRI8Muwq269OP5XE1gDBvwBIKufXWEVVPFY11zGXqU2tY7dUaLBjcJLdIQ5P5rGX/ZkS0fY6sRVNOG0IoXejXFWBKNls78UDdZ84Hher+PltboRj/5NY66Aaf1SyvzGWZIPlooGE9+qeXiQj++LhrtUD74IhQbt8fzcN+B4GKgujKD+dHLfbZvmqh0a17uR/FSrYqk52MK3jaty2Tv4YPJcLEvh2FJ4jOb2phwRtTZbSmvsZAXOty15wkcGfU6PS+O6A9T8BEOfgSs5iG5seiu5zXWCS7ZN8dhZbKt3Zu+cM2Do1hJLPpVPXXw3t+6FO2q1cMLY0JYFvwrDsvYRGvvHR39yfB2B/1HR/gOH2jOsNbh0nRfpHEA7Zadup9REGS2glWKm24vaMLFF/4pSnQJacC28oaImIpRgciROZERvhk7nRirmN9mWnShqxTeJm2MozzbA1H/J7Ig8pJWsohOBg0=
after_success: ./merge.sh $USERNAME $PASSWORD
